version: '3'
services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - hackmdPostgres
    restart: always
  app:
    image: hackmdio/hackmd:0.5.1
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
    ports:
      - "3000:3000"
    networks:
      backend:
    restart: always
networks:
  backend:

volumes:
  database:
